# Generated by Django 4.1.7 on 2023-03-06 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_post_timecreation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='timeCreation',
            field=models.DateField(auto_now_add=True),
        ),
    ]
